### ISSUE TITLE
Crashes immediately when battle start 

### ISSUE THREAD

**Issue by fullmetalarmour** [MlemandPurrs/ora-pink-dawn#3]
cnc-all-reboot-beta-v7.appimage crashes immediately when the enemy attack the base.

**Comment by fullmetalarmour** [comment]
OpenRA engine version release-20230225
OpenRA Language: en
Pink Dawn mod version cnc-all-reboot-beta-v7
on map fea3ba761f56f096454b1836da30a043314b5b2e (Frigid Pass by The Echo of Damnation).
Date: 2024-05-07 12:16:33Z
Operating System: Linux (X64, Unix 6.8.9.1)
Runtime Version: .NET CLR 6.0.28
Installed Language: sv (Installed) sv (Current) sv (Current UI)
Exception of type `System.IO.InvalidDataException`: nuyell5.aud is not a valid sound file!
   at OpenRA.Sound.LoadSound[T](String filename, Func`2 loadFormat) in /home/runner/work/ora-pink-dawn/ora-pink-dawn/engine/OpenRA.Game/Sound/Sound.cs:line 82
   at OpenRA.Sound.<>c__DisplayClass15_0.<Initialize>b__1(String filename) in /home/runner/work/ora-pink-dawn/ora-pink-dawn/engine/OpenRA.Game/Sound/Sound.cs:line 98
   at OpenRA.Exts.GetOrAdd[K,V](Dictionary`2 d, K k, Func`2 createFn) in /home/runner/work/ora-pink-dawn/ora-pink-dawn/engine/OpenRA.Game/Exts.cs:line 131
   at OpenRA.Sound.<PlayPredefined>g__PlaySound|80_0(<>c__DisplayClass80_0& ) in /home/runner/work/ora-pink-dawn/ora-pink-dawn/engine/OpenRA.Game/Sound/Sound.cs:line 407
   at OpenRA.Sound.PlayPredefined(SoundType soundType, Ruleset ruleset, Player p, Actor voicedActor, String type, String definition, String variant, Boolean relative, WPos pos, Single volumeModifier, Boolean attenuateVolume)
   at OpenRA.Mods.Common.Traits.Voiced.OpenRA.Traits.IVoiced.PlayVoiceLocal(Actor self, String phrase, String variant, Single volume) in /home/runner/work/ora-pink-dawn/ora-pink-dawn/engine/OpenRA.Mods.Common/Traits/Voiced.cs:line 63
   at OpenRA.VoiceExts.PlayVoiceLocal(Actor self, String phrase, Single volume) in /home/runner/work/ora-pink-dawn/ora-pink-dawn/engine/OpenRA.Game/VoiceExts.cs:line 40
   at OpenRA.Mods.Common.Traits.Sound.DeathSounds.OpenRA.Mods.Common.Traits.INotifyKilled.Killed(Actor self, AttackInfo e) in /home/runner/work/ora-pink-dawn/ora-pink-dawn/engine/OpenRA.Mods.Common/Traits/Sound/DeathSounds.cs:line 45
   at OpenRA.Mods.Common.Traits.Health.InflictDamage(Actor self, Actor attacker, Damage damage, Boolean ignoreModifiers) in /home/runner/work/ora-pink-dawn/ora-pink-dawn/engine/OpenRA.Mods.Common/Traits/Health.cs:line 221
   at OpenRA.Actor.InflictDamage(Actor attacker, Damage damage) in /home/runner/work/ora-pink-dawn/ora-pink-dawn/engine/OpenRA.Game/Actor.cs:line 481
   at OpenRA.Mods.Common.Warheads.DamageWarhead.InflictDamage(Actor victim, Actor firedBy, HitShape shape, WarheadArgs args) in /home/runner/work/ora-pink-dawn/ora-pink-dawn/engine/OpenRA.Mods.Common/Warheads/DamageWarhead.cs:line 89
   at OpenRA.Mods.Common.Warheads.SpreadDamageWarhead.DoImpact(WPos pos, Actor firedBy, WarheadArgs args) in /home/runner/work/ora-pink-dawn/ora-pink-dawn/engine/OpenRA.Mods.Common/Warheads/SpreadDamageWarhead.cs:line 123
   at OpenRA.Mods.Common.Warheads.DamageWarhead.DoImpact(Target& target, WarheadArgs args) in /home/runner/work/ora-pink-dawn/ora-pink-dawn/engine/OpenRA.Mods.Common/Warheads/DamageWarhead.cs:line 69
   at OpenRA.GameRules.WeaponInfo.Impact(Target& target, WarheadArgs args) in /home/runner/work/ora-pink-dawn/ora-pink-dawn/engine/OpenRA.Game/GameRules/WeaponInfo.cs:line 247
   at OpenRA.Mods.Common.Projectiles.Bullet.Explode(World world) in /home/runner/work/ora-pink-dawn/ora-pink-dawn/engine/OpenRA.Mods.Common/Projectiles/Bullet.cs:line 348
   at OpenRA.WorldUtils.DoTimed[T](IEnumerable`1 e, Action`1 a, String text) in /home/runner/work/ora-pink-dawn/ora-pink-dawn/engine/OpenRA.Game/WorldUtils.cs:line 75
   at OpenRA.World.Tick() in /home/runner/work/ora-pink-dawn/ora-pink-dawn/engine/OpenRA.Game/World.cs:line 448
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in /home/runner/work/ora-pink-dawn/ora-pink-dawn/engine/OpenRA.Game/Game.cs:line 639
   at OpenRA.Game.LogicTick() in /home/runner/work/ora-pink-dawn/ora-pink-dawn/engine/OpenRA.Game/Game.cs:line 654
   at OpenRA.Game.Loop() in /home/runner/work/ora-pink-dawn/ora-pink-dawn/engine/OpenRA.Game/Game.cs:line 823
   at OpenRA.Game.Run() in /home/runner/work/ora-pink-dawn/ora-pink-dawn/engine/OpenRA.Game/Game.cs:line 876
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/runner/work/ora-pink-dawn/ora-pink-dawn/engine/OpenRA.Game/Game.cs:line 308
   at OpenRA.Launcher.Program.Main(String[] args) in /home/runner/work/ora-pink-dawn/ora-pink-dawn/engine/OpenRA.Launcher/Program.cs:line 32

**Comment by fullmetalarmour** [comment]
Same with previous version.
OpenRA engine version release-20230225
OpenRA Language: en
Pink Dawn mod version cnc-all-reboot-beta-v6
on map 21d6b06d257c68518b61229448aec34a04915d8a (Boreal Fissure by The Echo of Damnation).
Date: 2024-05-07 12:40:46Z
Operating System: Linux (X64, Unix 6.8.9.1)
Runtime Version: .NET CLR 6.0.28
Installed Language: sv (Installed) sv (Current) sv (Current UI)
Exception of type `System.IO.InvalidDataException`: nuyell3.aud is not a valid sound file!
   at OpenRA.Sound.LoadSound[T](String filename, Func`2 loadFormat) in /home/runner/work/ora-pink-dawn/ora-pink-dawn/engine/OpenRA.Game/Sound/Sound.cs:line 82
   at OpenRA.Sound.<PlayPredefined>g__PlaySound|80_0(<>c__DisplayClass80_0& ) in /home/runner/work/ora-pink-dawn/ora-pink-dawn/engine/OpenRA.Game/Sound/Sound.cs:line 407
   at OpenRA.Sound.PlayPredefined(SoundType soundType, Ruleset ruleset, Player p, Actor voicedActor, String type, String definition, String variant, Boolean relative, WPos pos, Single volumeModifier, Boolean attenuateVolume)
   at OpenRA.Mods.Common.Traits.Voiced.OpenRA.Traits.IVoiced.PlayVoiceLocal(Actor self, String phrase, String variant, Single volume) in /home/runner/work/ora-pink-dawn/ora-pink-dawn/engine/OpenRA.Mods.Common/Traits/Voiced.cs:line 63
   at OpenRA.VoiceExts.PlayVoiceLocal(Actor self, String phrase, Single volume) in /home/runner/work/ora-pink-dawn/ora-pink-dawn/engine/OpenRA.Game/VoiceExts.cs:line 40
   at OpenRA.Mods.Common.Traits.Sound.DeathSounds.OpenRA.Mods.Common.Traits.INotifyKilled.Killed(Actor self, AttackInfo e) in /home/runner/work/ora-pink-dawn/ora-pink-dawn/engine/OpenRA.Mods.Common/Traits/Sound/DeathSounds.cs:line 45
   at OpenRA.Mods.Common.Traits.Health.InflictDamage(Actor self, Actor attacker, Damage damage, Boolean ignoreModifiers) in /home/runner/work/ora-pink-dawn/ora-pink-dawn/engine/OpenRA.Mods.Common/Traits/Health.cs:line 221
   at OpenRA.Mods.Common.Warheads.SpreadDamageWarhead.DoImpact(WPos pos, Actor firedBy, WarheadArgs args) in /home/runner/work/ora-pink-dawn/ora-pink-dawn/engine/OpenRA.Mods.Common/Warheads/SpreadDamageWarhead.cs:line 123
   at OpenRA.GameRules.WeaponInfo.Impact(Target& target, WarheadArgs args) in /home/runner/work/ora-pink-dawn/ora-pink-dawn/engine/OpenRA.Game/GameRules/WeaponInfo.cs:line 247
   at OpenRA.Mods.Common.Projectiles.Missile.Explode(World world) in /home/runner/work/ora-pink-dawn/ora-pink-dawn/engine/OpenRA.Mods.Common/Projectiles/Missile.cs:line 929
   at OpenRA.Mods.Common.Projectiles.Missile.Tick(World world)
   at OpenRA.WorldUtils.DoTimed[T](IEnumerable`1 e, Action`1 a, String text) in /home/runner/work/ora-pink-dawn/ora-pink-dawn/engine/OpenRA.Game/WorldUtils.cs:line 75
   at OpenRA.World.Tick() in /home/runner/work/ora-pink-dawn/ora-pink-dawn/engine/OpenRA.Game/World.cs:line 448
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in /home/runner/work/ora-pink-dawn/ora-pink-dawn/engine/OpenRA.Game/Game.cs:line 639
   at OpenRA.Game.LogicTick() in /home/runner/work/ora-pink-dawn/ora-pink-dawn/engine/OpenRA.Game/Game.cs:line 654
   at OpenRA.Game.Loop() in /home/runner/work/ora-pink-dawn/ora-pink-dawn/engine/OpenRA.Game/Game.cs:line 823
   at OpenRA.Game.Run() in /home/runner/work/ora-pink-dawn/ora-pink-dawn/engine/OpenRA.Game/Game.cs:line 876
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/runner/work/ora-pink-dawn/ora-pink-dawn/engine/OpenRA.Game/Game.cs:line 308
   at OpenRA.Launcher.Program.Main(String[] args) in /home/runner/work/ora-pink-dawn/ora-pink-dawn/engine/OpenRA.Launcher/Program.cs:line 32

**Comment by fullmetalarmour** [comment]
Update!
Tried on my second disk (Fedora) works without problem I do not have Ultimate Collection and or Remastered Collection from Steam installed on that disk and I imported from the freeware isos from cnc-comm instead so I suspect that importing from Steam Ultimate Collection/Remastered Collection breaks the mod somehow.

**Comment by MlemandPurrs** [comment]
most strange issue, it seems like a sound file was missing that was supposed to be included and present in the base game files, somehow ?!?
